conventions:
  attn_mask_key: attention_mask
  x_key: input_ids
  y_key: labels
core:
  entity: dansolombrinoandfriends
  project_name: higher-order-task-arithmetics
  storage_dir: ${oc.env:PROJECT_ROOT}/storage
  tags:
  - dev
  version: 0.0.1
defaults:
- hydra: default
- nn: default
- train: default
- _self_
epoch_divisor: None
eval_datasets:
- CoLA
- SST2
- MRPC
- QQP
- MNLI
- QNLI
- RTE
eval_on_train: false
misc:
  cache_dir: null
  ckpt_path: ${oc.env:PROJECT_ROOT}/checkpoints/${nn.module.model.model_name}
  openclip_cachedir: ${oc.env:PROJECT_ROOT}/checkpoints/openclip_cache
  pretrained_checkpoint: ${misc.ckpt_path}/zeroshot.pt
order: 1
seed_index: 0
task_vectors:
  aggregator:
    _target_: tvp.task_vectors.aggregator.SumAggregator
    mean: true
  breadcrumbs_beta: 0.85
  breadcrumbs_gamma: 0.993
  merging_method: normal
  num_task_vectors: 8
  orthogonalize: false
  scaling_coefficient: 1
  ties_lambda: 1
  ties_topk: 0.15
  to_apply:
  - CoLA
  - SST2
  - MRPC
  - QQP
  - MNLI
  - QNLI
  - RTE
