
defaults:
  - _self_
  # - model: vit
  #- model: roberta
  - model: bert

# _target_: tvp.pl_module.image_classifier.ImageClassifier
_target_: tvp.pl_module.text_classifier.TextClassifier
x_key: ${conventions.x_key}
y_key: ${conventions.y_key}
attn_mask_key: ${conventions.attn_mask_key}
encoder: ??
classifier: ??

optimizer:
  _target_: torch.optim.Adam
  lr: 1e-5
  # _target_: torch.optim.SGD
  # lr: 0.1
  # momentum: 0.9
  # weight_decay: 1e-4

# lr_scheduler:
#   _target_: pl_bolts.optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
#   warmup_epochs: 5
#   max_epochs: ${train.trainer.max_epochs}
#   warmup_start_lr: 1e-6
#   eta_min: 0.0
#   last_epoch: -1
